### ISSUE TITLE
enumflags! macro

### ISSUE THREAD

**Issue by Mr-Byte** [dx-rs/dx_core#1]
Write a macro called enumflags! That creates scoped, type-safe bit flags.

**Comment by athre0z** [comment]
Just a hint in case this project is still active: there is such a thing built right into std:
http://doc.rust-lang.org/0.12.0/std/macro.bitflags!.html

**Comment by Mr-Byte** [comment]
Sorry I didn't respond earlier, I do plan to continue working on this project.

I've looked at bitflags, and was kind of disappointed that it declared the individual flags as globals, but the more I look into it, the more I think I'll just be using bitflags instead of trying to roll my own solution.  I'll close this solution in favor of using bitflags.
